#!/bin/bash
# SPDX-License-Identifier: GPL-2.0

. common/fio_common
. common/nbd_common

echo "run perf test via ublk-nbd(queues: 2, jobs: 2, nbd server: $NBDSRV:nbdkit memory $NBD_SIZE)"

file=`_create_image "nbd" "none" $NBD_SIZE`

export T_TYPE_PARAMS="-t nbd -q 2 -d 127 --host $NBDSRV"
__run_dev_perf 2

_remove_image "nbd" $file
