#!/bin/bash

. common/fio_common

echo -e "\trun fio with delete ubd-loop test"

DEV=/dev/ubdb0
BS=4k
RW=rw
JOBS=4
QUEUES=4
RUNTIME=10
LOOPS=10

CNT=0
while [ $CNT -lt $LOOPS ]; do
	__create_ubd_dev "loop" $QUEUES
	echo -e "\trun fio on ubd with delete $CNT"
	__run_fio_libaio "/dev/ubdb0" $BS $RW $JOBS $RUNTIME > /dev/null 2 >& 1 &
	sleep 4
	RES=`__remove_ubd_dev_return 0`
	if [ $RES -ne 0 ]; then
			echo -e "\tdelete ubd0 failed"
			ps -eLf | grep ubd
			(cd /sys/kernel/debug/block/ubdb0 && find . -type f -exec grep -aH . {} \;)
			break
	fi
	wait 
	let CNT++
done
