#!/bin/bash

. common/fio_common

ublk_run_mount_test()
{
	echo -n -e "\tmount/umount ublk device with root fstype(pin page $1, uring_comp: $2)..."
	__create_ublk_dev "loop" $QUEUES $1 $2

	ROOT_FSTYPE=`findmnt -l -o FSTYPE -n /`

	wipefs -a $DEV
	eval mkfs.${ROOT_FSTYPE} $DEV > /dev/null 2>&1

	mount $DEV  $MNT > /dev/null 2>&1

	UBLK_FSTYPE=`findmnt -l -o FSTYPE -n $MNT`
	if [ "$UBLK_FSTYPE" = "$ROOT_FSTYPE" ]; then
			echo "ok"
	else
			echo "failed"
	fi
	umount $MNT > /dev/null 2>&1

	__remove_ublk_dev 0
}

DEV=/dev/ublkb0
QUEUES=2
MNT=`mktemp -d`
URING_COMP=1

for PIN_PAGE in `seq 0 1`; do
	ublk_run_mount_test $PIN_PAGE $URING_COMP
done

rm -fr $MNT
