#!/bin/bash
# SPDX-License-Identifier: MIT or GPL-2.0-only

. common/fio_common
. common/loop_common

echo -e "\trun fio with delete ublk-loop test, requests owned by the server"

# 1M writes to a backing file keep requests with the server far longer than
# a null device does, which is where a teardown that waits on them wedges
BS=1M
RW=write
JOBS=4
RT=$TRUNTIME
LOOPS=2
RES=0

FILE=`_create_loop_image "data" $LO_IMG_SZ`
export T_TYPE_PARAMS="-t loop -q 2 -d 64 -r 0 -f $FILE"
for CNT in `seq $LOOPS`; do
	__ublk_run_del_mid_io loop-del $CNT $BS $RW $JOBS $RT || RES=1
done
_remove_loop_image $FILE

exit $RES
