#!/bin/bash

export TEST_DIR=$(cd "$(dirname "$0")";pwd)

. $TEST_DIR/fio_common

UBD=$TEST_DIR/../ubd

JOBS=2
QUEUES=4
RTIME=10

FN="$TEST_DIR/loop_001.img"
truncate -s 5G  $FN

$UBD del -a > /dev/null 2>&1

echo "running fio with deleting ubd disk"

DEVS=/dev/ubdb0
BS=4k
RW=rw

QD=128
BATCH=16

CNT=0

while [ $CNT -le 16 ]; do
	echo -e "\tfio with delete test $CNT"
	$UBD add -t loop -q $QUEUES -f $FN -d 256
	fio --bs=$BS --ioengine=libaio --iodepth=$QD --iodepth_batch_submit=$BATCH \
		--iodepth_batch_complete_min=$BATCH --filename=$DEVS \
		--direct=1 --runtime=$RTIME --numjobs=$JOBS --rw=$RW \
		--name=test --group_reporting > /dev/null 2>&1 &
	sleep 4
	$UBD del -n 0

	if [ $? -ne 0 ]; then
			echo -e "\tdelete ubd0 failed"
			ps -eLf | grep ubd
			(cd /sys/kernel/debug/block/ubdb0 && find . -type f -exec grep -aH . {} \;)
			journalctl -r | grep ubd | grep -v systemd | head -n 200
			break
	fi
	wait 
	let CNT++
done

rm -f $FN
