'\" t
.\"     Title: ublk
.\"    Author: [FIXME: author] [see http://www.docbook.org/tdg5/en/html/author]
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 07/16/2025
.\"    Manual: ublk: manage ublk devices
.\"    Source: ublk
.\"  Language: English
.\"
.TH "UBLK" "1" "07/16/2025" "ublk" "ublk: manage ublk devices"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
ublk \- Utility to manage ublk devices
.SH "SYNOPSIS"
.HP \w'\fBublk\ <command>\ [<command\ options>]\ [<type\ specific\ options>]\fR\ 'u
\fBublk <command> [<command options>] [<type specific options>]\fR
.SH "DESCRIPTION"
.PP
ublk is a utility that allows you to create, recover, view or delete user\-space block devices\&.
.PP
ublk by default comes with several different types of devices, such as iscsi, nbd, nfs, null and loop\&.
.PP
The following commands are supported:
.SH "ADD COMMAND"
.PP
Command to add a ublk device\&.
.PP
\fB add {\-t, \-\-type} TYPE [{\-n, \-\-number} DEV_ID] [{\-q, \-\-queues} NR_HW_QUEUES] [{\-d, \-\-depth} QUEUE_DEPTH] [{\-u, \-\-uring_comp} URING_COMP] [{\-g, \-\-need\-get\-data} NEED_GET_DATA] [{\-r, \-\-user_recovery} {0|1}] [{\-i, \-\-user_recovery_reissue} {0|1}] [{\-e, \-\-user_recovery_fail_io} {0|1}] [\-\-debug_mask=0x{DBG_MASK}] [\-\-unprivileged] [\-\-usercopy] [\-\-max_io_buf_bytes={BYTES}] [{\-z, \-\-zerocopy}] [<type specific options>] \fR
.PP
\fB\-t, \-\-type\fR
.RS 4
Specifies the type of device to create\&. The five types of supported devices are iscsi, nbd, nfs, null and loop\&.
.RE
.PP
\fB\-n, \-\-number\fR
.RS 4
Create a device with this id\&. The device node will be /dev/ublkb_n_\&.
.RE
.PP
\fB\-q, \-\-queue\fR
.RS 4
Number of queues to create\&. Each queue is services by a dedicated child process\&. Default is 1\&.
.RE
.PP
\fB\-d, \-\-depth\fR
.RS 4
Maximum queue\-depthfor each queue\&. Default is 4096\&.
.RE
.PP
\fB\-u, \-\-uring_comp\fR
.RS 4
Force to complete io cmd via io_uring_cmd_complete_in_task so that performance comparison is done easily with using task_work_add\&.
.RE
.PP
\fB\-g, \-\-need_get_data\fR
.RS 4
User should issue io cmd again for write requests to set io buffer address and copy data from bio vectors to the userspace io buffer\&.
.RE
.PP
\fB\-r, \-\-user_recovey\fR
.RS 4
Block devices are recoverable if ublk server exits and restarts\&. Outstanding I/O when ublk server exits is met with errors\&. I/O issued while there is no ublk server queues\&.
.RE
.PP
\fB\-i, \-\-user_recovey_reissue\fR
.RS 4
Block devices are recoverable if ublk server exits and restarts Outstanding I/O when ublk server exits is reissued I/O issued while there is no ublk server queues
.RE
.PP
\fB\-e, \-\-user_recovey_fail_io\fR
.RS 4
Block devices are recoverable if ublk server exits and restarts Outstanding I/O when ublk server exits is met with errors I/O issued while there is no ublk server is met with errors
.RE
.PP
\fB\-\-debug_mask\fR
.RS 4
Bitmask specifying which debug features to enable\&.
.RE
.PP
\fB\-\-max_io_buf_bytes\fR
.RS 4
Maximum I/O size\&. Default is 512kb\&.
.sp
NOTE: Memory buffers are pre\-allocated with one buffer for each entry in queue_depth\&.
.RE
.PP
\fB\-\-unprivileged\fR
.RS 4
Unprivileged user can create /dev/ublkcN and /dev/ublkbN\&.
.sp
/dev/ublk\-control needs to be available for unprivileged user, and it can be done via udev rule to make all control commands available to unprivileged user\&. Except for the command of UBLK_CMD_ADD_DEV, all other commands are only allowed for the owner of the specified device\&.
.sp
When userspace sends UBLK_CMD_ADD_DEV, the device pair\*(Aqs owner_uid and owner_gid are stored to ublksrv_ctrl_dev_info by kernel, so far only the current user\*(Aqs uid/gid is stored, that said owner of the created device is always the current user\&.
.sp
We still need udev rule to apply OWNER/GROUP with the stored owner_uid and owner_gid\&.
.sp
Then ublk server can be run as unprivileged user, and /dev/ublkbN can be accessed and managed by its owner represented by owner_uid/owner_gid\&.
.RE
.PP
\fB\-\-user_copy\fR
.RS 4
Copy between request and user buffer by pread()/pwrite()
.RE
.PP
\fB\-z, \-\-zerocopy\fR
.RS 4
Zero\-copy is based on io\-uring uring_cmd of REGISTER_IO_BUF & UNREGISTER_IO_BUF, which avoids data copy between ublk frontend request buffer and ublk server buffer, so memory bandwidth is saved, and throughput & latency improvement can be often observed on large I/O size
.sp
This requires Linux kernel 6\&.15 or later\&.
.RE
.SS "NULL"
.PP
The null device type does not take any extra options\&.
.SS "LOOP"
.PP
Extra options for the loop device type:
.PP
\fB add \-t loop \&.\&.\&. {\-f, \-\-file} FILE [\-\-buffered_io] [\-o, \-\-offset OFFSET] \fR
.PP
\fB\-f, \-\-file\fR
.RS 4
File to use as backing storage for the loop device\&.
.RE
.PP
\fB\-\-buffered_io\fR
.RS 4
Use buffered i/o for accessing the backing file\&. Default is direct i/o\&.
.RE
.PP
\fB\-\-offset\fR
.RS 4
Offset skips first NUM sectors on backing file\&.
.RE
.PP
Example: Create a loop block device
.sp
.if n \{\
.RS 4
.\}
.nf
    # ublk add \-t loop \-n 0 \-f 10M\&.raw
  
.fi
.if n \{\
.RE
.\}
.sp
.SS "NBD"
.PP
Extra options for the nbd (Network Block Device) device type:
.PP
\fB add \-t nbd \&.\&.\&. {\-\-host HOST | \-\-unix UNIX_PATH} \-\-export_name EXP_NAME [\-\-send_zc] [\-\-read_only] \fR
.PP
\fB\-\-host\fR
.RS 4
Hostname of NBD server\&.
.RE
.PP
\fB\-\-host\fR
.RS 4
Hostname of NBD server to use\&.
.RE
.PP
\fB\-\-unix\fR
.RS 4
Path to unix domain socket to use to talk to NBD\&.
.RE
.PP
\fB\-\-export_name\fR
.RS 4
Name of NBD export\&.
.RE
.PP
\fB\-\-send_zc\fR
.RS 4
Use Zero\-Copy\&.
.RE
.PP
\fB\-\-read_only\fR
.RS 4
Read\-only device\&.
.RE
.SS "NFS"
.PP
Extra options for the nfs device type:
.PP
\fB add \-t nfs \&.\&.\&. \-\-nfs NFS\-URL \fR
.PP
\fB\-\-nfs NFS\-URL\fR
.RS 4
URL to the NFS file to use as the block device\&.
.sp
The NFS\-URL format is describe in the libnfs README: https://github\&.com/sahlberg/libnfs/blob/9fa155bfa9d34347a669fbecf4a64259cc573724/README#L55
.RE
.PP
Example: Create a nfs block device
.sp
.if n \{\
.RS 4
.\}
.nf
    # ublk add \-t nfs \-n 0 \-\-nfs nfs://10\&.0\&.0\&.1/export/10M\&.raw
  
.fi
.if n \{\
.RE
.\}
.sp
.SS "iSCSI"
.PP
Extra options for the iSCSI device type\&. iSCSI support requires libiscsi 1\&.20\&.3 or later\&.
.PP
\fB add \-t iscsi \&.\&.\&. \-\-iscsi ISCSI\-URL \-\-initiator\-name NAME \fR
.PP
\fB\-\-iscsi ISCSI\-URL\fR
.RS 4
URL to the iSCSI device to use as the block device\&.
.sp
The ISCSI\-URL format is describe in the libiscsi README: https://github\&.com/sahlberg/libiscsi/blob/eb19863f77e2bad4799ceb90e47fa3bc6205233e/README\&.md?plain=1#L37
.RE
.PP
\fB\-\-initiator\-name NAME\fR
.RS 4
The initiator name to use when logging in to the target\&.
.RE
.PP
Example: Create an iSCSI block device
.sp
.if n \{\
.RS 4
.\}
.nf
    # ublk add \-t iscsi \-n 0 \-\-iscsi iscsi://iscsi\-stgt/iqn\&.2001\-04\&.com\&.ronnie\&.sr0/1 \-\-initiator\-name iqn\&.ronnie\&.test
  
.fi
.if n \{\
.RE
.\}
.sp
.SH "DEL COMMAND"
.PP
Command to delete a ublk device\&.
.PP
\fB del {\-n, \-\-number} DEV_ID [\-a, \-\-all] [\-\-async] \fR
.PP
\fB\-n, \-\-number\fR
.RS 4
Delete the device with this id\&.
.RE
.PP
\fB\-a, \-\-all\fR
.RS 4
Delete all devices\&.
.RE
.PP
Example: Deleting a loop block device
.sp
.if n \{\
.RS 4
.\}
.nf
    # ublk del \-n 0
  
.fi
.if n \{\
.RE
.\}
.sp
.SH "SET_AFFINITY COMMAND"
.PP
Command to change queue affinity\&.
.PP
\fB set_affinity {\-n, \-\-number} DEV_ID [\-q, \-\-queue] QID \-\-cpuset="[SET]" \fR
.PP
\fB\-n, \-\-number\fR
.RS 4
Change the affinity on this device\&.
.RE
.PP
\fB\-q, \-\-queue\fR
.RS 4
Which queue to change the affinity for\&.
.RE
.PP
\fB\-\-cpuset="[SET]"\fR
.RS 4
The new cpuset for this device/queue\&. Format is a comma\-separated list of CPUs within squre brackets\&.
.RE
.PP
Example: Set affinity to core 7 for device 0, queue 1
.sp
.if n \{\
.RS 4
.\}
.nf
    # ublk set_affinity \-n 0 \-q 1 \-\-cpuset="[7]"
  
.fi
.if n \{\
.RE
.\}
.sp
.SH "LIST COMMAND"
.PP
List one or all devices and show their configutaion\&.
.PP
\fB list {\-n, \-\-number} DEV_ID [\-v, \-\-verbose] \fR
.PP
\fB\-n, \-\-number\fR
.RS 4
List the device with this id\&. If omitted all devices will be listed
.RE
.PP
\fB\-v, \-\-verbose\fR
.RS 4
Verbose listing\&. Include the JSON device arguments in the output\&.
.RE
.SH "RECOVER COMMAND"
.PP
Recover a failed ublk device\&.
.PP
\fB recover {\-n, \-\-number} DEV_ID \fR
.PP
\fB\-n, \-\-number\fR
.RS 4
Device to recover\&.
.RE
.SH "FEATURES COMMAND"
.PP
Show supported features for the ublk driver\&.
.PP
\fB features \fR
.SH "HELP COMMAND"
.PP
Show generic ot type specific help\&.
.PP
\fB help [{\-t, \-\-type} TYPE] \fR
.PP
\fB\-t, \-\-type\fR
.RS 4
Show help page\&. It \-t is specified, show help page for the specific device type\&.
.RE
.SH "VERSION"
.PP
Show help page\&.\&.
.PP
\fB {\-v, \-\-version} \fR
.SH "RECOVERY"
.PP
There are three arguments that control how ublk will behave in case of a failure, such as crashing\&. The default behavior is no recovery and the device will fail and be removed once the target exists\&.
.PP
To enable recovery mode set "\-\-recovery 1" on the command line\&. Then instead of removing the device upon failure it will instead become inactive in a quiesced state\&.
.sp
.if n \{\
.RS 4
.\}
.nf
dev id 0: nr_hw_queues 1 queue_depth 128 block size 4096 dev_capacity 20480
    max rq size 524288 daemon pid 1239110 state QUIESCED
    flags 0x4a [ URING_CMD_COMP_IN_TASK RECOVERY CMD_IOCTL_ENCODE ]
    ublkc: 511:0 ublkb: 259:4 owner: 0:0
    queue 0: tid 1239112 affinity(0 1 2 3 4 5 6 7 )
    target {"backing_file":"10M","dev_size":10485760,"direct_io":1,"name":"loop","offset":0,"type":0}
  
.fi
.if n \{\
.RE
.\}
.sp
In this state the block device still exists but no I/O can be performed\&.
.PP
To recover a QUIESCED device you can use the recover command:
\fB ublk recover \-n DEV_ID \fR
.PP
There are two additional flags that control how ublk will handle I/O that were in flight when a device is recovered\&.
.SS "\-\-user_recovery_reissue 1"
.PP
When the device is recovered ublk will reissue any I/O that were in flight\&.
.SS "\-\-user_recovery_fail_io 1"
.PP
When the device is recovered ublk will fail all I/O and return an error back to the application\&.
.SH "SEE ALSO"
.PP
\m[blue]\fB\%http://github.com/ublk-org/ublksrv\fR\m[]
