#!/bin/bash
# SPDX-License-Identifier: GPL-2.0

export NBDSRV=127.0.0.1
export NBD_SIZE=2G

_create_nbd_image() {
	local type=$1
	local my_size=$2
	local my_file=`mktemp -p ${UBLK_TMP_DIR}  ublk_nbd_${type}_${my_size}_XXXXX`

	which nbdkit > /dev/null 2>&1
	[ $? -ne 0 ] && echo "please install nbdkit package" && exit -1

	killall -9 nbdkit > /dev/null 2>&1

	if [ $type == "none" ]; then
		nbdkit memory $my_size
	elif [ $type == "nullb" ]; then
		modprobe -r null_blk
		modprobe null_blk
		my_file="/dev/nullb0"
		nbdkit file $my_file
	else
		truncate -s ${my_size} ${my_file}

		my_size=`stat --printf="%s" ${my_file}`
		local my_count=`expr ${my_size} / 1048576`
		dd if=/dev/zero of=$my_file bs=1M count=${my_count} oflag=direct > /dev/null 2>&1

		nbdkit file $my_file
	fi
	sleep 1
	echo $my_file
}

_remove_nbd_image() {
	local file=$1

	sleep 2
	killall -9 nbdkit > /dev/null 2>&1

	if [ "$file" == "/dev/nullb0" ]; then
		modprobe -r null_blk
	else
		[ -f "$file" ] && rm -f $file
	fi
}
