#!/bin/bash
# SPDX-License-Identifier: GPL-2.0

. common/fio_common
. common/qcow2_common

echo "run perf test on empty qcow2 image via nbd"

file=`_create_qcow2_image "null" $QCOW2_IMG_SZ`

export T_TYPE="qemu-nbd"
export T_TYPE_PARAMS="-c /dev/nbd11 -n --aio=native $file"

__run_nbd_dev_perf 1

_remove_qcow2_image $file
